#!/bin/bash

mv	ADD_GOOD.C	ADD_GOOD.js
mv	ADD_PL.C	ADD_PL.js
mv	DEL_PL.C	DEL_PL.js
mv	DRAW_PL.C	DRAW_PL.js
mv	HITCOLID.C	HITCOLID.js
mv	MOVE_PL.C	MOVE_PL.js
mv	SETCLEAN.C	SETCLEAN.js
mv	SPIRALS.C	SPIRALS.js
mv	SPIRHELP.C	SPIRHELP.js
mv	TESTTRIG.C	TESTTRIG.js
mv	VISIT_PL.C	VISIT_PL.js


